<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Appointments Report</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            line-height: 1.5;
            margin: 0;
            padding: 0;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #4a90e2;
            padding-bottom: 10px;
        }

        .report-title {
            font-size: 24px;
            font-weight: bold;
            color: #1a365d;
            margin: 0;
        }

        .report-date {
            font-size: 14px;
            color: #718096;
        }

        .stats-container {
            width: 100%;
            margin-bottom: 20px;
        }

        .stat-box {
            width: 30%;
            display: inline-block;
            background: #f7fafc;
            padding: 10px;
            border-radius: 8px;
            text-align: center;
        }

        .stat-label {
            font-size: 10px;
            text-transform: uppercase;
            color: #4a5568;
            margin-bottom: 5px;
        }

        .stat-value {
            font-size: 18px;
            font-weight: bold;
            color: #2d3748;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th {
            background-color: #4a90e2;
            color: white;
            text-align: left;
            padding: 10px;
            font-size: 12px;
            text-transform: uppercase;
        }

        td {
            padding: 10px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 11px;
        }

        tr:nth-child(even) {
            background-color: #f8fafc;
        }

        .status-badge {
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .status-completed {
            background: #c6f6d5;
            color: #22543d;
        }

        .status-scheduled {
            background: #bee3f8;
            color: #2a4365;
        }

        .status-cancelled {
            background: #fed7d7;
            color: #742a2a;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #a0aec0;
            padding: 10px 0;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1 class="report-title">Appointments Report</h1>
        <p class="report-date">
            Period: {{ \Carbon\Carbon::parse($start)->format('M d, Y') }} -
            {{ \Carbon\Carbon::parse($end)->format('M d, Y') }}
        </p>
    </div>

    <div class="stats-container">
        <div class="stat-box">
            <div class="stat-label">Total Appointments</div>
            <div class="stat-value">{{ $data->count() }}</div>
        </div>
        <div class="stat-box">
            <div class="stat-label">Completed</div>
            <div class="stat-value">{{ $data->where('status', 'completed')->count() }}</div>
        </div>
        <div class="stat-box">
            <div class="stat-label">Cancelled</div>
            <div class="stat-value">{{ $data->where('status', 'cancelled')->count() }}</div>
        </div>
    </div>



    <table>
        <thead>
            <tr>
                <th>Date & Time</th>
                <th>Patient Name</th>
                <th>Doctor</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($data as $appointment)
                <tr>
                    <td>{{ \Carbon\Carbon::parse($appointment->appointment_time)->format('M d, Y h:i A') }}</td>
                    <td>
                        <strong>{{ $appointment->patient?->name ?? 'Deleted Patient' }}</strong><br>
                        <span style="color: #718096;">{{ $appointment->patient?->phone }}</span>
                    </td>
                    <td>Dr. {{ $appointment->doctor?->name ?? 'N/A' }}</td>
                    <td>
                        <span class="status-badge status-{{ $appointment->status }}">
                            {{ $appointment->status }}
                        </span>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Clinic Management System on {{ now()->format('F j, Y, g:i a') }}
    </div>
</body>

</html>
