<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Patient Analysis Report</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            line-height: 1.4;
        }

        .header {
            margin-bottom: 30px;
        }

        .report-title {
            font-size: 24px;
            color: #44337a;
            margin-bottom: 5px;
        }

        .report-meta {
            font-size: 12px;
            color: #6b46c1;
            font-weight: bold;
        }

        .grid {
            width: 100%;
            margin-bottom: 20px;
        }

        .grid td {
            width: 50%;
            vertical-align: top;
        }

        .card {
            background: #faf5ff;
            border: 1px solid #e9d8fd;
            padding: 15px;
            border-radius: 10px;
            margin-right: 10px;
        }

        .card-label {
            font-size: 10px;
            color: #6b46c1;
            text-transform: uppercase;
            font-weight: bold;
        }

        .card-value {
            font-size: 20px;
            font-weight: bold;
            color: #44337a;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th {
            border-bottom: 2px solid #6b46c1;
            text-align: left;
            padding: 12px 8px;
            font-size: 11px;
            color: #44337a;
        }

        td {
            padding: 10px 8px;
            border-bottom: 1px solid #e9d8fd;
            font-size: 10px;
        }

        .tag {
            padding: 3px 7px;
            border-radius: 10px;
            font-size: 9px;
            font-weight: bold;
        }

        .tag-high {
            background: #fed7e2;
            color: #9b2c2c;
        }

        /* High frequency patient */
        .tag-regular {
            background: #e9d8fd;
            color: #44337a;
        }

        .footer {
            position: fixed;
            bottom: 10;
            width: 100%;
            text-align: center;
            font-size: 9px;
            color: #718096;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1 class="report-title">Patient Database Report</h1>
        <div class="report-meta">Total Registered Patients: {{ $data->count() }}</div>
    </div>

    <table class="grid">
        <tr>
            <td>
                <div class="card">
                    <div class="card-label">Active (Has Appointments)</div>
                    <div class="card-value">{{ $data->filter(fn($p) => $p->appointments->count() > 0)->count() }}</div>
                </div>
            </td>
            <td>
                <div class="card" style="margin-right:0;">
                    <div class="card-label">New This Month</div>
                    <div class="card-value">{{ $data->where('created_at', '>=', now()->startOfMonth())->count() }}</div>
                </div>
            </td>
        </tr>
    </table>

    <table>
        <thead>
            <tr>
                <th>Patient Details</th>
                <th>Joined Date</th>
                <th>Visits</th>
                <th>Last Visit</th>
                <th>Medical History Snippet</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($data as $patient)
                <tr>
                    <td>
                        <strong>{{ $patient->name }}</strong><br>
                        <span style="color: #718096;">{{ $patient->phone }}</span>
                    </td>
                    <td>{{ $patient->created_at->format('M d, Y') }}</td>
                    <td style="text-align: center;">
                        <span class="tag {{ $patient->appointments->count() > 5 ? 'tag-high' : 'tag-regular' }}">
                            {{ $patient->appointments->count() }}
                        </span>
                    </td>
                    <td>{{ $patient->appointments->max('appointment_time') ? \Carbon\Carbon::parse($patient->appointments->max('appointment_time'))->format('M d, Y') : 'Never' }}
                    </td>
                    <td style="color: #718096;">{{ Str::limit($patient->past_medical_history ?? 'None', 40) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Clinic Management System - Total Records: {{ $data->count() }}
    </div>
</body>

</html>
